####################
#   Your Profile   #
####################
title: your blog title
lang: ko
email: your-email@example.com
description: your description
twitter_username: your_twitter_username_without_@
github_username:  your_github_username_without_#

###############
#    build    #
###############
baseurl: ""
url: ""
markdown: kramdown
plugins:
  - jekyll-seo-tag